// Network Wars — native engine + MCTS (RED player).
//
// Mechanics ported 1:1 from ../game.js. The ONLY randomness in the game is the
// battle dice (p=0.55 attacker-win coin flips). The 4 bots are deterministic.
//
// Fairness: real battles use a per-board RNG stream seeded from the board seed;
// MCTS rollouts use a SEPARATE per-thread RNG stream. The search never observes
// the real battle stream, so there is no seed/dice exploitation.
//
// Input (stdin): boards generated by JS (matches sim.js board distribution).
// Output (stdout): aggregate win rate. Boards are played in parallel (pthreads).

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include <pthread.h>
#include <unistd.h>
#include <time.h>

// decision-timing instrumentation (use with --threads 1 for clean numbers)
static long g_dec_count=0; static double g_dec_ns=0;
static inline double now_ns(void){ struct timespec t; clock_gettime(CLOCK_MONOTONIC,&t);
  return t.tv_sec*1e9 + t.tv_nsec; }

#define MAXN 32
#define MAXDEG 8
#define NFAC 5            // red=0 green=1 yellow=2 blue=3 purple=4
#define WIN_NODES 24
#define ATT_P 0.55
#define MAX_TURNS 120     // games unresolved by here are losses anyway (real wins ~turn 8);
                          // also caps rollout length, killing the slow-tail pathology

// ----------------------------------------------------------------------------
// RNG: splitmix64 seeding + xoshiro256-ish; cheap uniform doubles.
// ----------------------------------------------------------------------------
typedef struct { uint64_t s; } Rng;
static inline uint64_t sm64(uint64_t *x){ uint64_t z=(*x+=0x9E3779B97F4A7C15ULL);
  z=(z^(z>>30))*0xBF58476D1CE4E5B9ULL; z=(z^(z>>27))*0x94D049BB133111EBULL; return z^(z>>31);}
static inline void rng_seed(Rng*r,uint64_t seed){ r->s=seed?seed:0x123456789ULL; }
static inline double rng_d(Rng*r){ return (sm64(&r->s)>>11)*(1.0/9007199254740992.0); }

// ----------------------------------------------------------------------------
// Board (immutable per game) + mutable state.
// ----------------------------------------------------------------------------
typedef struct {
  int N;
  int deg[MAXN];
  int adj[MAXN][MAXDEG];
} Board;

typedef struct {
  int8_t owner[MAXN];     // 0..4
  int16_t str[MAXN];
} State;

static const Board *B;    // thread-local set per game via tls? we pass explicitly.

// capture-probability table for rollout heuristic (a attacker stack, d defender)
static double PCAP[66][66];
static void init_pcap(void){
  for(int a=0;a<66;a++) for(int d=0;d<66;d++){
    if(a<=1){PCAP[a][d]=0;continue;}
    if(d<=0){PCAP[a][d]=1;continue;}
    int n=d+a-2; double prob=0, term=pow(1-ATT_P,n);
    for(int k=0;k<=n;k++){ if(k>=d) prob+=term; term=term*(ATT_P/(1-ATT_P))*((double)(n-k)/(k+1)); }
    if(prob>1)prob=1; PCAP[a][d]=prob;
  }
}
static inline double capprob(int a,int d){ if(a>65)a=65; if(d>65)d=65; if(a<0)a=0; if(d<0)d=0; return PCAP[a][d]; }

// E[captured node strength | capture] (= codex expectedCapturedStrength).
static double ECAP[66][66];
static void init_ecap(void){
  double p=ATT_P;
  for(int a=0;a<66;a++) for(int d=0;d<66;d++){
    if(a<2||d<1){ECAP[a][d]=0;continue;}
    double pd=pow(p,d), term=pd, psum=term, wsum=term*(a-1);
    for(int j=1;j<=a-2;j++){ term*=(1-p)*((double)(d-1+j)/(double)j); psum+=term; wsum+=term*(a-1-j); }
    ECAP[a][d]= psum>0? wsum/psum : 0;
  }
}
static inline double ecap(int a,int d){ if(a>65)a=65; if(d>65)d=65; if(a<0)a=0; if(d<0)d=0; return ECAP[a][d]; }

// ----------------------------------------------------------------------------
// Core mechanics
// ----------------------------------------------------------------------------
static inline void count_all(const Board*b,const State*s,int*c){
  c[0]=c[1]=c[2]=c[3]=c[4]=0;
  for(int i=0;i<b->N;i++) c[s->owner[i]]++;
}
// returns faction 0..4 winner, or -1 if none
static inline int winner(const Board*b,const State*s){
  int c[NFAC]; count_all(b,s,c);
  for(int f=0;f<NFAC;f++) if(c[f]>=WIN_NODES) return f;
  int alive=-1,na=0;
  for(int f=0;f<NFAC;f++) if(c[f]>0){alive=f;na++;}
  return na==1?alive:-1;
}

// resolve a full battle from->to using rng r. caller guarantees legality.
static inline int resolve(const Board*b,State*s,int from,int to,Rng*r){
  int a=s->str[from], d=s->str[to];
  // last striker (a==2) spent clearing the final defender: captures the node but
  // can't spread -> captured node ends at 0.
  while(a>1 && d>0){ if(rng_d(r)<ATT_P){ d--; if(d==0&&a==2) a--; } else a--; }
  if(d==0){ s->owner[to]=s->owner[from]; s->str[to]=a-1; s->str[from]=1; return 1; }
  s->str[from]=a; s->str[to]=d; return 0;
}

// reinforce: largest connected component (earliest on tie) gets +size spread over
// its border nodes (sorted ascending id), round-robin.
static int comp_buf[MAXN], seen_buf[MAXN], border_buf[MAXN];
static void reinforce(const Board*b,State*s,int fac){
  int seen[MAXN]={0};
  int bestComp[MAXN], bestSize=0;
  for(int i=0;i<b->N;i++){
    if(s->owner[i]!=fac||seen[i]) continue;
    int comp[MAXN], cs=0, stack[MAXN], sp=0;
    stack[sp++]=i; seen[i]=1;
    while(sp){ int id=stack[--sp]; comp[cs++]=id;
      for(int k=0;k<b->deg[id];k++){int nb=b->adj[id][k]; if(!seen[nb]&&s->owner[nb]==fac){seen[nb]=1;stack[sp++]=nb;}}
    }
    if(cs>bestSize){ bestSize=cs; memcpy(bestComp,comp,cs*sizeof(int)); }
  }
  if(bestSize==0) return;
  // border = comp nodes with a non-fac neighbor, sorted ascending (comp already
  // discovered in mixed order; sort)
  int border[MAXN], bn=0;
  for(int i=0;i<bestSize;i++){ int id=bestComp[i];
    for(int k=0;k<b->deg[id];k++){ if(s->owner[b->adj[id][k]]!=fac){ border[bn++]=id; break; } }
  }
  if(bn==0) return;
  // insertion sort ascending
  for(int i=1;i<bn;i++){int v=border[i],j=i-1; while(j>=0&&border[j]>v){border[j+1]=border[j];j--;} border[j+1]=v;}
  for(int i=0;i<bestSize;i++) s->str[border[i%bn]]++;
}

// best bot move: weakest strictly-beatable enemy neighbor; tie-break def asc, atk
// desc, from asc, to asc. returns 1 if found.
static inline int best_bot_move(const Board*b,const State*s,int fac,int*of,int*ot){
  int bf=-1,bt=-1,bdef=0,batk=0;
  for(int i=0;i<b->N;i++){
    if(s->owner[i]!=fac||s->str[i]<=1) continue;
    int atk=s->str[i];
    for(int k=0;k<b->deg[i];k++){ int nb=b->adj[i][k];
      if(s->owner[nb]==fac) continue; int def=s->str[nb];
      if(def>=atk) continue;
      if(bf<0 || def<bdef || (def==bdef&&atk>batk) || (def==bdef&&atk==batk&&i<bf)
         || (def==bdef&&atk==batk&&i==bf&&nb<bt)){ bf=i;bt=nb;bdef=def;batk=atk; }
    }
  }
  if(bf<0) return 0; *of=bf;*ot=bt; return 1;
}

static inline int has_faction(const Board*b,const State*s,int fac){
  for(int i=0;i<b->N;i++) if(s->owner[i]==fac) return 1; return 0;
}

// run a full bot turn (attacks then reinforce). returns winner or -1.
static inline int run_bot(const Board*b,State*s,int fac,Rng*r){
  if(!has_faction(b,s,fac)) return -1;
  int of,ot,guard=0;
  while(guard++<1000 && best_bot_move(b,s,fac,&of,&ot)){
    resolve(b,s,of,ot,r);
    int w=winner(b,s); if(w>=0) return w;
  }
  reinforce(b,s,fac);
  return -1;
}

// run all 4 bots in order. returns winner or -1.
static inline int run_all_bots(const Board*b,State*s,Rng*r){
  for(int f=1;f<=4;f++){ int w=run_bot(b,s,f,r); if(w>=0) return w; }
  return -1;
}

// ----------------------------------------------------------------------------
// Rollout (default) policy for RED. Fast greedy with capture-prob floor,
// component-growth + leader-denial scoring. Returns when no good attack.
// ----------------------------------------------------------------------------
// largest component size for RED, optionally pretending flip is RED-owned.
static int largest_red_comp(const Board*b,const State*s,int flip){
  int seen[MAXN]={0}, best=0;
  for(int i=0;i<b->N;i++){
    int owned = (i==flip)||s->owner[i]==0;
    if(!owned||seen[i]) continue;
    int sz=0, stack[MAXN], sp=0; stack[sp++]=i; seen[i]=1;
    while(sp){int id=stack[--sp]; sz++;
      for(int k=0;k<b->deg[id];k++){int nb=b->adj[id][k]; int o=(nb==flip)||s->owner[nb]==0; if(o&&!seen[nb]){seen[nb]=1;stack[sp++]=nb;}}}
    if(sz>best)best=sz;
  }
  return best;
}

// rollout tuning weights (global, set from argv)
static double RP_FLOOR=0.10, RP_GROW=10, RP_PC=2, RP_LEAD=1;
// post-fix: a 2-stack attack (attacker==2) that wins captures a 0-strength node
// and drops the attacker to 1 — usually wasteful. RP_2PEN discourages it in the
// rollout (0 = original behavior). Skipped when the capture itself ends the game.
static double RP_2PEN=0;
static int g_srollout=0;     // use the strong (codex evaluatePosition) rollout

// --- codex evaluatePosition, ported (DEFAULT_WEIGHTS) ------------------------
// red component info: number of comps + membership of the largest comp.
static void red_comp_info(const Board*b,const State*s,int*ncomp,int*inLargest,int*largestLen){
  int seen[MAXN]={0}; int nc=0, bestSize=0, bestStart=-1;
  int compOf[MAXN]; for(int i=0;i<b->N;i++)compOf[i]=-1;
  for(int i=0;i<b->N;i++){
    if(s->owner[i]!=0||seen[i])continue;
    int sz=0,stack[MAXN],sp=0; stack[sp++]=i; seen[i]=1; int cid=nc;
    while(sp){int id=stack[--sp]; sz++; compOf[id]=cid;
      for(int k=0;k<b->deg[id];k++){int nb=b->adj[id][k]; if(s->owner[nb]==0&&!seen[nb]){seen[nb]=1;stack[sp++]=nb;}}}
    if(sz>bestSize){bestSize=sz;bestStart=cid;} nc++;
  }
  for(int i=0;i<b->N;i++) inLargest[i]= (s->owner[i]==0 && compOf[i]==bestStart);
  *ncomp=nc; *largestLen=bestSize;
}

static double EW_redCount=150,EW_largest=95,EW_redStr=5,EW_largeStr=6,EW_borderStr=5,
  EW_split=42,EW_weakBorder=13,EW_botThreat=95,EW_enemyCount=17,EW_nextAtk=16,
  EW_kill=90,EW_win=1000000,EW_attackThresh=7;

static double evalpos(const Board*b,const State*s){
  int c[NFAC]; count_all(b,s,c);
  if(c[0]>=WIN_NODES) return EW_win + c[0]*10000;
  if(c[0]==0) return -EW_win;
  int ncomp,largestLen,inL[MAXN]; red_comp_info(b,s,&ncomp,inL,&largestLen);
  double redStr=0,largeStr=0,borderStr=0,weakBorder=0,botThreat=0,nextAtk=0;
  for(int i=0;i<b->N;i++){
    if(s->owner[i]!=0) continue;
    int st=s->str[i]; redStr+=st; if(inL[i]) largeStr+=st;
    int hasEnemy=0;
    for(int k=0;k<b->deg[i];k++){ int nb=b->adj[i][k]; if(s->owner[nb]==0) continue; hasEnemy=1;
      if(s->str[nb]>st){ double pc=capprob(s->str[nb],st); botThreat+=pc*(9+(inL[i]?5:0)); } }
    if(hasEnemy){ borderStr+=st; if(st<=2) weakBorder+=3-st; }
  }
  // nextAttackBonus over legal red moves
  for(int i=0;i<b->N;i++){ if(s->owner[i]!=0||s->str[i]<=1)continue;
    for(int k=0;k<b->deg[i];k++){int nb=b->adj[i][k]; if(s->owner[nb]==0)continue;
      double pc=capprob(s->str[i],s->str[nb]); if(pc>0.35) nextAtk+=pc*(1+(s->str[nb]<=2?0.7:0)); } }
  double score=0;
  score+=c[0]*EW_redCount; score+=largestLen*EW_largest; score+=redStr*EW_redStr;
  score+=largeStr*EW_largeStr; score+=borderStr*EW_borderStr;
  score-=(ncomp>1?ncomp-1:0)*EW_split; score-=weakBorder*EW_weakBorder;
  score-=botThreat*EW_botThreat; score+=nextAtk*EW_nextAtk;
  for(int f=1;f<=4;f++){ score-=c[f]*EW_enemyCount; if(c[f]==0) score+=EW_kill; }
  return score;
}

// strong rollout: greedy on expected post-move evalpos; stop below threshold.
static int srollout_pick(const Board*b,State*s,int*of,int*ot){
  double base=evalpos(b,s);
  int bf=-1,bt=-1; double bs=-1e18;
  for(int i=0;i<b->N;i++){ if(s->owner[i]!=0||s->str[i]<=1)continue; int atk=s->str[i];
    for(int k=0;k<b->deg[i];k++){ int nb=b->adj[i][k]; if(s->owner[nb]==0)continue; int def=s->str[nb];
      double pc=capprob(atk,def);
      // capture state (expected)
      int8_t oOwn=s->owner[nb]; int16_t oF=s->str[i], oT=s->str[nb];
      int ec=(int)(ecap(atk,def)+0.5); if(ec<1)ec=1;
      s->owner[nb]=0; s->str[nb]=ec; s->str[i]=1;
      double evCap=evalpos(b,s);
      s->owner[nb]=oOwn; s->str[nb]=oT; s->str[i]=oF;
      // fail state (attacker spent)
      s->str[i]=1; double evFail=evalpos(b,s); s->str[i]=oF;
      double sc=pc*evCap+(1-pc)*evFail;
      if(sc>bs){bs=sc;bf=i;bt=nb;} } }
  if(bf<0) return 0;
  if(bs <= base + EW_attackThresh) return 0;
  *of=bf;*ot=bt; return 1;
}

// pick one rollout attack for RED; returns 1 with from/to, else 0 (stop turn).
static int rollout_pick(const Board*b,const State*s,int*of,int*ot){
  int c[NFAC]; count_all(b,s,c);
  int cur=largest_red_comp(b,s,-1);
  int bf=-1,bt=-1; double bs=-1e18;
  int mf=-1,mt=-1; double mp=-1;       // best-odds fallback
  for(int i=0;i<b->N;i++){
    if(s->owner[i]!=0||s->str[i]<=1) continue; int atk=s->str[i];
    for(int k=0;k<b->deg[i];k++){ int nb=b->adj[i][k]; if(s->owner[nb]==0) continue;
      int def=s->str[nb]; double pc=capprob(atk,def);
      if(pc>mp){mp=pc;mf=i;mt=nb;}
      if(pc<RP_FLOOR) continue;
      int grow=largest_red_comp(b,s,nb)-cur;
      double sc=grow*RP_GROW + pc*RP_PC + c[s->owner[nb]]*RP_LEAD;
      // discourage wasteful 2-stack captures (win => 0-strength node, atk->1),
      // unless capturing this node would win the game outright.
      if(RP_2PEN>0 && atk==2 && c[0]+1<WIN_NODES) sc-=RP_2PEN;
      if(sc>bs){bs=sc;bf=i;bt=nb;}
    }
  }
  if(bf>=0){*of=bf;*ot=bt;return 1;}
  if(mf>=0){*of=mf;*ot=mt;return 1;}   // mop up best odds rather than gift bots a turn
  return 0;
}

// finish RED's current turn with the rollout policy.
static int rollout_red_turn(const Board*b,State*s,Rng*r){
  int of,ot,guard=0;
  while(guard++<200 && (g_srollout? srollout_pick(b,s,&of,&ot) : rollout_pick(b,s,&of,&ot))){
    resolve(b,s,of,ot,r);
    int w=winner(b,s); if(w>=0) return w;
  }
  return -1;
}

static int g_rollhorizon=0;     // 0 => full game; else cap rollout at N rounds
static int g_leafeval=0;        // map horizon state via evalpos logistic
// NOTE: these defaults are MISCALIBRATED for the 7x6 rules. On real decisions
// evalpos ranges ~[-23000,7000] (mean ~-2500), so sigmoid((evalpos-1600)/650)
// saturates wrong (BCE ~5.1). Calibrated scalar is ref~-5000 scale~4800 (BCE
// ~0.57, still marginal). The richer --vvalue (8-feature logistic, BCE ~0.25) is
// a far better value. Always calibrate before using --leafeval/--vmix. See
// FINDINGS.md. Left as-is to preserve historical behavior.
static double g_evRef=1600, g_evScale=650;
static double g_vmix=0;         // AlphaGo-style leaf value mix: (1-vmix)*rollout_z + vmix*logistic(evalpos@leaf)
// forward decls for the learned value (Exp D2), defined further below
static int g_vvalue;
static inline double learned_value(const Board*b,const State*s);

static inline double leaf_value(const Board*b,const State*s){
  if(g_vvalue) return learned_value(b,s);
  if(g_leafeval){ double e=evalpos(b,s); return 1.0/(1.0+exp(-(e-g_evRef)/g_evScale)); }
  int c[NFAC]; count_all(b,s,c);
  int me=c[1]; for(int f=2;f<=4;f++) if(c[f]>me)me=c[f];
  double v=0.5+(c[0]-me)/48.0; if(v<0)v=0; if(v>1)v=1; return v;
}

// play out to terminal from "RED to move, start of turn". returns value in [0,1].
// With g_vmix>0, blends the AlphaGo way: the entry-leaf positional logistic is
// mixed with the rollout-to-terminal result, (1-vmix)*z + vmix*e0. vmix=0 is the
// original pure-rollout behavior.
static double playout_from_red(const Board*b,State*s,Rng*r){
  double e0=0; if(g_vmix>0) e0 = g_vvalue ? learned_value(b,s)
                                          : 1.0/(1.0+exp(-(evalpos(b,s)-g_evRef)/g_evScale));
  double z; int w, done=0; int H = g_rollhorizon>0 ? g_rollhorizon : MAX_TURNS;
  for(int t=0;t<H;t++){
    w=rollout_red_turn(b,s,r); if(w>=0){ z=w==0?1:0; done=1; break; }
    reinforce(b,s,0); w=winner(b,s); if(w>=0){ z=w==0?1:0; done=1; break; }
    w=run_all_bots(b,s,r); if(w>=0){ z=w==0?1:0; done=1; break; }
  }
  if(!done) z=leaf_value(b,s);
  return g_vmix>0 ? (1.0-g_vmix)*z + g_vmix*e0 : z;
}

// ----------------------------------------------------------------------------
// Flat-UCB per-attack search. At a real RED decision (mid-turn ok), enumerate
// all legal attacks + STOP, evaluate each by rollouts, return best.
//   returns 1 -> attack (*of,*ot); 0 -> stop turn.
// ----------------------------------------------------------------------------
typedef struct { int from,to; } Move;

static int red_legal(const Board*b,const State*s,Move*out){
  int n=0;
  for(int i=0;i<b->N;i++){ if(s->owner[i]!=0||s->str[i]<=1) continue;
    for(int k=0;k<b->deg[i];k++){int nb=b->adj[i][k]; if(s->owner[nb]!=0){out[n].from=i;out[n].to=nb;n++;}}}
  return n;
}

static int g_budget=2000;
static double g_c=1.4;
static double g_stopMargin=0.0;

// evaluate one candidate (idx==nMoves means STOP) once; returns rollout value.
static inline double eval_candidate(const Board*b,const State*root,const Move*mv,int nMoves,int idx,Rng*r){
  State s; memcpy(&s,root,sizeof(State));
  if(idx==nMoves){
    // STOP: reinforce red, bots, then play out from red's next turn
    reinforce(b,&s,0); int w=winner(b,&s); if(w>=0) return w==0?1:0;
    w=run_all_bots(b,&s,r); if(w>=0) return w==0?1:0;
    return playout_from_red(b,&s,r);
  } else {
    resolve(b,&s,mv[idx].from,mv[idx].to,r); int w=winner(b,&s); if(w>=0) return w==0?1:0;
    // finish the turn with rollout policy, then continue
    w=rollout_red_turn(b,&s,r); if(w>=0) return w==0?1:0;
    reinforce(b,&s,0); w=winner(b,&s); if(w>=0) return w==0?1:0;
    w=run_all_bots(b,&s,r); if(w>=0) return w==0?1:0;
    return playout_from_red(b,&s,r);
  }
}

static int choose_red(const Board*b,const State*root,Rng*r,int*of,int*ot){
  Move mv[256]; int nm=red_legal(b,root,mv);
  if(nm==0) return 0;
  int K=nm+1;                 // candidates incl STOP at index nm
  static __thread double sumW[257]; static __thread int nn[257];
  for(int i=0;i<K;i++){sumW[i]=0;nn[i]=0;}
  // seed each once
  for(int i=0;i<K;i++){ sumW[i]+=eval_candidate(b,root,mv,nm,i,r); nn[i]=1; }
  for(int total=K; total<g_budget; total++){
    double lt=log((double)total); int bi=0; double bu=-1e18;
    for(int i=0;i<K;i++){ double u=sumW[i]/nn[i]+g_c*sqrt(lt/nn[i]); if(u>bu){bu=u;bi=i;} }
    sumW[bi]+=eval_candidate(b,root,mv,nm,bi,r); nn[bi]++;
  }
  int bi=0; double bm=-1e18;
  for(int i=0;i<K;i++){ double m=sumW[i]/nn[i]; if(m>bm){bm=m;bi=i;} }
  // require attack to beat STOP mean by margin
  double stopMean=sumW[nm]/nn[nm];
  if(bi==nm) return 0;
  if(sumW[bi]/nn[bi] < stopMean+g_stopMargin) return 0;
  *of=mv[bi].from; *ot=mv[bi].to; return 1;
}

// ----------------------------------------------------------------------------
// Multi-turn open-loop UCT. The tree branches on RED actions (attacks + STOP).
// A STOP edge applies reinforce+bots (sampled dice) and lands on the next RED
// turn, so the tree spans many turns; rollout only fills the un-expanded tail.
// Open-loop: state is re-sampled every traversal, children keyed by action id.
// ----------------------------------------------------------------------------
#define MAXCH 64           // max candidate actions per node (incl STOP)
#define ACT_STOP (-1)
// PUCT node. Candidate actions (priAct/priP) are fixed at node creation from the
// creation-time state; children are created lazily as PUCT selects them.
typedef struct {
  int visits; double sumW;
  int ncand;                 // number of candidate actions (priAct[0..ncand-1])
  int   priAct[MAXCH];       // action id (ACT_STOP allowed)
  float priP[MAXCH];         // policy prior
  int   child[MAXCH];        // child node index, -1 if not yet expanded
  int   cvis[MAXCH];         // child visit count (cached for PUCT)
  double cw[MAXCH];          // child value sum (cached for PUCT)
  double cw2[MAXCH];         // child value sum-of-squares (for LCB root selection)
} Node;

typedef struct { Node*pool; int cap; int used; } Pool;

static inline int pool_alloc(Pool*p){ return p->used++; }

// apply an action to state; STOP => reinforce(red)+bots. uses rollout rng.
static inline void apply_action(const Board*b,State*s,int act,Rng*r){
  if(act==ACT_STOP){ reinforce(b,s,0); if(winner(b,s)>=0) return; run_all_bots(b,s,r); }
  else { resolve(b,s,act>>5,act&31,r); }   // from = act>>5, to = act&31  (N<=32)
}

static int g_tree_budget=4000;   // tuned winner: ~80% on the dev set
static int g_selmean=1;          // pick highest-mean root action (beats most-visited)
static int g_minVisits=80;       // ignore root actions with < this many visits
static int g_prior=0;            // unused (kept for CLI compat)
static double g_cpuct=2.5;
static double g_temp=8.0;        // softmax temperature for the policy prior (uniform when unused)
static double g_fpu=0.5;         // first-play urgency value for unvisited children
static double g_stopLogit=0; // additive logit for the STOP action's prior
static double g_lcb=0;       // root selection: pick max (mean - lcb*stderr) instead of max mean

static int g_strongprior=0;  // use evalpos-based move scores for the PUCT prior

// ---- distillation feature dump (Exp C): record per-root-decision candidate
// features + the search's resulting visit counts, to fit a learned prior. ----
static int g_dumpfeat=0; static FILE* g_dumpf=NULL; static long g_decid=0;
static pthread_mutex_t g_dumpmu=PTHREAD_MUTEX_INITIALIZER;
// Exp D: per-decision (evalpos(root), search win-prob) for value calibration.
// g_dumpvfmode=1 dumps VFEAT state features instead of scalar evalpos (Exp D2).
static int g_dumpval=0; static FILE* g_dumpvf=NULL; static int g_dumpvfmode=0;
// shared feature extractor: NFEAT features for an action from state s0 (RED to move).
#define NFEAT 9
static void action_features(const Board*b,const State*s0,int act,const int*c,int cur,double*f){
  if(act==ACT_STOP){ f[0]=0;f[1]=0;f[2]=0;f[3]=0;f[4]=0;f[5]=0;f[6]=0;f[7]=0;f[8]=1; return; }
  int from=act>>5,to=act&31; int atk=s0->str[from],def=s0->str[to];
  double pc=capprob(atk,def), ec=ecap(atk,def);
  int grow=largest_red_comp(b,s0,to)-cur;
  int defLeader=c[s0->owner[to]];
  f[0]=pc; f[1]=ec/8.0; f[2]=grow; f[3]=defLeader/8.0;
  f[4]=(def<=2)?1:0; f[5]=atk/8.0; f[6]=def/8.0; f[7]=b->deg[to]/8.0; f[8]=0; // f8=STOP indicator
}
// ---- Exp D2: richer learned VALUE. State features -> search win-prob. ----
#define VFEAT 8
static void state_vfeatures(const Board*b,const State*s,double*vf){
  int c[NFAC]; count_all(b,s,c);
  int ncomp,largestLen,inL[MAXN]; red_comp_info(b,s,&ncomp,inL,&largestLen);
  double redStr=0,borderStr=0,botThreat=0; int sumEnemy=0,maxEnemy=0;
  for(int f=1;f<=4;f++) if(c[f]>maxEnemy) maxEnemy=c[f];
  for(int i=0;i<b->N;i++){
    if(s->owner[i]==0){ redStr+=s->str[i]; int hasE=0;
      for(int k=0;k<b->deg[i];k++){ int nb=b->adj[i][k]; if(s->owner[nb]!=0){ hasE=1;
        if(s->str[nb]>s->str[i]) botThreat+=capprob(s->str[nb],s->str[i]); } }
      if(hasE) borderStr+=s->str[i];
    } else sumEnemy+=s->str[i];
  }
  vf[0]=c[0]/24.0; vf[1]=largestLen/24.0; vf[2]=ncomp/6.0; vf[3]=redStr/40.0;
  vf[4]=borderStr/40.0; vf[5]=maxEnemy/24.0; vf[6]=sumEnemy/80.0; vf[7]=botThreat/10.0;
}
static int g_vvalue=0; static double VW[VFEAT+1]={0};
static void load_vvalue(const char*path){
  FILE*fp=fopen(path,"r"); if(!fp){fprintf(stderr,"vvalue: cannot open %s\n",path);return;}
  for(int i=0;i<VFEAT+1;i++) if(fscanf(fp,"%lf",&VW[i])!=1){fprintf(stderr,"vvalue: short\n");break;}
  fclose(fp); g_vvalue=1;
}
static inline double learned_value(const Board*b,const State*s){
  double vf[VFEAT]; state_vfeatures(b,s,vf);
  double z=VW[VFEAT]; for(int k=0;k<VFEAT;k++) z+=VW[k]*vf[k];
  return 1.0/(1.0+exp(-z));
}
// learned linear prior (Exp C): weights[0..NFEAT-1] dot features + bias = logit.
static int g_lprior=0; static double LW[NFEAT+1]={0};
static void load_lprior(const char*path){
  FILE*fp=fopen(path,"r"); if(!fp){fprintf(stderr,"lprior: cannot open %s\n",path);return;}
  for(int i=0;i<NFEAT+1;i++) if(fscanf(fp,"%lf",&LW[i])!=1){fprintf(stderr,"lprior: short file\n");break;}
  fclose(fp); g_lprior=1;
}

// Fill a node's candidate actions + policy priors from state s (RED to move).
static void init_node(const Board*b,const State*s0,Node*nd){
  nd->visits=0; nd->sumW=0;
  Move mv[256]; int nm=red_legal(b,s0,mv);
  int c[NFAC]; count_all(b,s0,c);
  int cur=largest_red_comp(b,s0,-1);
  (void)c; (void)cur;
  double sc[257]; int act[257]; int n=0;
  double base = g_strongprior ? evalpos(b,s0) : 0;
  State tmp; if(g_strongprior) memcpy(&tmp,s0,sizeof(State));
  for(int i=0;i<nm && n<MAXCH-1;i++){
    int from=mv[i].from,to=mv[i].to;
    int atk=s0->str[from], def=s0->str[to];
    if(g_lprior){
      double f[NFEAT]; action_features(b,s0,(from<<5)|to,c,cur,f);
      double z=LW[NFEAT]; for(int k=0;k<NFEAT;k++) z+=LW[k]*f[k];
      sc[n]=z;
    } else if(g_strongprior){
      double pc=capprob(atk,def);
      int8_t oOwn=tmp.owner[to]; int16_t oF=tmp.str[from], oT=tmp.str[to];
      int ec=(int)(ecap(atk,def)+0.5); if(ec<1)ec=1;
      tmp.owner[to]=0; tmp.str[to]=ec; tmp.str[from]=1; double evCap=evalpos(b,&tmp);
      tmp.owner[to]=oOwn; tmp.str[to]=oT; tmp.str[from]=oF;
      tmp.str[from]=1; double evFail=evalpos(b,&tmp); tmp.str[from]=oF;
      sc[n]=(pc*evCap+(1-pc)*evFail - base)/200.0;   // scaled advantage over "stay"
    } else {
      sc[n]=0;                                        // uniform prior (fast)
    }
    act[n]=(from<<5)|to; n++;
  }
  // STOP candidate
  if(g_lprior){ double f[NFEAT]; action_features(b,s0,ACT_STOP,c,cur,f);
    double z=LW[NFEAT]; for(int k=0;k<NFEAT;k++) z+=LW[k]*f[k]; sc[n]=z+g_stopLogit; }
  else sc[n]=g_stopLogit;
  act[n]=ACT_STOP; n++;
  // softmax with temperature -> priors
  double mx=-1e18; for(int i=0;i<n;i++) if(sc[i]>mx)mx=sc[i];
  double sum=0; for(int i=0;i<n;i++){ sc[i]=exp((sc[i]-mx)/g_temp); sum+=sc[i]; }
  for(int i=0;i<n;i++){ nd->priAct[i]=act[i]; nd->priP[i]=(float)(sc[i]/sum);
    nd->child[i]=-1; nd->cvis[i]=0; nd->cw[i]=0; nd->cw2[i]=0; }
  nd->ncand=n;
}

// is an attack action currently legal in state s?
static inline int act_legal(const State*s,int act){
  if(act==ACT_STOP) return 1;
  int from=act>>5, to=act&31;
  return s->owner[from]==0 && s->str[from]>1 && s->owner[to]!=0;
}

static __thread Pool g_pool={0};

// One PUCT simulation from root state.
static double puct_sim(const Board*b,Pool*pool,int root,const State*root_s,Rng*r){
  State s; memcpy(&s,root_s,sizeof(State));
  int path[700]; int slotPath[700]; int pl=0;
  int node=root;
  double value;
  for(;;){
    int w=winner(b,&s); if(w>=0){ value=(w==0)?1.0:0.0; break; }
    if(pl>=690){ value=playout_from_red(b,&s,r); break; }
    Node*nd=&pool->pool[node];
    double sq=sqrt((double)(nd->visits)+1.0);
    int bestSlot=-1; double bestU=-1e18;
    for(int i=0;i<nd->ncand;i++){
      int a=nd->priAct[i];
      if(!act_legal(&s,a)) continue;
      double q = nd->cvis[i]>0 ? nd->cw[i]/nd->cvis[i] : g_fpu;
      double u = q + g_cpuct*nd->priP[i]*sq/(1.0+nd->cvis[i]);
      if(u>bestU){bestU=u;bestSlot=i;}
    }
    if(bestSlot<0){ value=playout_from_red(b,&s,r); break; }
    path[pl]=node; slotPath[pl]=bestSlot; pl++;
    int act=nd->priAct[bestSlot];
    apply_action(b,&s,act,r);
    if(nd->child[bestSlot]<0){
      // expand: create child, compute its priors, rollout
      int ci=pool_alloc(pool); pool->pool[node].child[bestSlot]=ci;
      // node ptr may be stale after alloc? pool is fixed array -> safe
      if(winner(b,&s)<0) init_node(b,&s,&pool->pool[ci]);
      else { pool->pool[ci].ncand=0; pool->pool[ci].visits=0; pool->pool[ci].sumW=0; }
      value=playout_from_red(b,&s,r);
      break;
    }
    node=pool->pool[node].child[bestSlot];
  }
  // backprop along edges (update cached child stats) and node totals
  for(int i=0;i<pl;i++){ Node*n=&pool->pool[path[i]]; int sl=slotPath[i];
    n->visits++; n->sumW+=value; n->cvis[sl]++; n->cw[sl]+=value; n->cw2[sl]+=value*value; }
  return value;
}

// choose RED's next action via multi-turn PUCT. returns 1=attack,0=stop.
static int choose_red_tree(const Board*b,const State*root_s,Rng*r,int*of,int*ot){
  Move mv[256]; int nm=red_legal(b,root_s,mv);
  if(nm==0) return 0;
  int need=g_tree_budget+8;
  if(g_pool.cap<need){ free(g_pool.pool); g_pool.pool=malloc(sizeof(Node)*need); g_pool.cap=need; }
  g_pool.used=0;
  int root=pool_alloc(&g_pool);
  init_node(b,root_s,&g_pool.pool[root]);
  for(int i=0;i<g_tree_budget;i++) puct_sim(b,&g_pool,root,root_s,r);
  // pick root action: most-visited (robust) or highest-mean (--selmean)
  Node*rn=&g_pool.pool[root];
  if(g_dumpfeat && g_dumpf){
    int c[NFAC]; count_all(b,root_s,c); int cur=largest_red_comp(b,root_s,-1);
    pthread_mutex_lock(&g_dumpmu);
    long did=g_decid++;
    for(int i=0;i<rn->ncand;i++){
      double f[NFEAT]; action_features(b,root_s,rn->priAct[i],c,cur,f);
      double mean=rn->cvis[i]?rn->cw[i]/rn->cvis[i]:0;
      fprintf(g_dumpf,"%ld",did);
      for(int k=0;k<NFEAT;k++) fprintf(g_dumpf," %.4f",f[k]);
      fprintf(g_dumpf," %d %.4f\n",rn->cvis[i],mean);
    }
    pthread_mutex_unlock(&g_dumpmu);
  }
  if(g_dumpval && g_dumpvf){
    double wp=rn->visits? rn->sumW/rn->visits : 0.5;
    pthread_mutex_lock(&g_dumpmu);
    if(g_dumpvfmode){ double vf[VFEAT]; state_vfeatures(b,root_s,vf);
      for(int k=0;k<VFEAT;k++) fprintf(g_dumpvf,"%.4f ",vf[k]);
      fprintf(g_dumpvf,"%.4f\n",wp);
    } else { double ev=evalpos(b,root_s); fprintf(g_dumpvf,"%.2f %.4f\n",ev,wp); }
    pthread_mutex_unlock(&g_dumpmu);
  }
  int bestAct=ACT_STOP, bestVis=-1; double bestMean=-1, bestScore=-1e18;
  for(int i=0;i<rn->ncand;i++){
    if(rn->cvis[i] < g_minVisits) continue;
    double mean=rn->cvis[i]?rn->cw[i]/rn->cvis[i]:0;
    if(g_selmean){
      double score=mean;
      if(g_lcb>0 && rn->cvis[i]>1){            // lower-confidence-bound on the win-prob estimate
        double var=rn->cw2[i]/rn->cvis[i]-mean*mean; if(var<0)var=0;
        score=mean - g_lcb*sqrt(var/rn->cvis[i]);
      }
      if(score>bestScore){ bestScore=score; bestAct=rn->priAct[i]; bestVis=rn->cvis[i]; }
    } else if(rn->cvis[i]>bestVis || (rn->cvis[i]==bestVis && mean>bestMean)){
      bestVis=rn->cvis[i]; bestMean=mean; bestAct=rn->priAct[i]; } }
  if(bestAct==ACT_STOP) return 0;
  *of=bestAct>>5; *ot=bestAct&31; return 1;
}

// ----------------------------------------------------------------------------
// Full game: RED uses MCTS (re-plan per attack), bots deterministic. realRng =
// battle dice (board seed); search uses a separate rollout rng.
// ----------------------------------------------------------------------------
static int g_maxAttacks=80;
static int g_use_tree=1;   // multi-turn UCT by default; --flat for the old per-attack search
static int play_game(const Board*b,State*s,uint64_t boardSeed,uint64_t rolloutSeed){
  Rng real; rng_seed(&real, sm64(&(uint64_t){boardSeed}));   // real battle stream
  Rng roll; rng_seed(&roll, sm64(&(uint64_t){rolloutSeed})); // search stream (independent)
  for(int turn=0; turn<MAX_TURNS; turn++){
    int w=winner(b,s); if(w>=0) return w;
    // RED turn: re-plan per attack
    for(int a=0;a<g_maxAttacks;a++){
      int c[NFAC]; count_all(b,s,c); if(c[0]>=WIN_NODES) return 0;
      int of,ot; double _t0=now_ns();
      int act = g_use_tree ? choose_red_tree(b,s,&roll,&of,&ot)
                           : choose_red(b,s,&roll,&of,&ot);
      g_dec_ns += now_ns()-_t0; g_dec_count++;
      if(!act) break;
      resolve(b,s,of,ot,&real);
      if(winner(b,s)>=0) break;
    }
    w=winner(b,s); if(w>=0) return w;
    reinforce(b,s,0); w=winner(b,s); if(w>=0) return w;
    w=run_all_bots(b,s,&real); if(w>=0) return w;
  }
  return winner(b,s);
}

// pure-greedy RED (= safeExpand) for engine-parity validation.
static int play_game_greedy(const Board*b,State*s,uint64_t boardSeed){
  Rng real; rng_seed(&real, sm64(&(uint64_t){boardSeed}));
  for(int turn=0;turn<MAX_TURNS;turn++){
    int w=winner(b,s); if(w>=0) return w;
    int of,ot,guard=0;
    while(guard++<1000 && best_bot_move(b,s,0,&of,&ot)){ resolve(b,s,of,ot,&real); if(winner(b,s)>=0)break; }
    w=winner(b,s); if(w>=0) return w;
    reinforce(b,s,0); w=winner(b,s); if(w>=0) return w;
    w=run_all_bots(b,s,&real); if(w>=0) return w;
  }
  return winner(b,s);
}

// ----------------------------------------------------------------------------
// Batch input / parallel driver
// ----------------------------------------------------------------------------
typedef struct { Board b; State s0; uint64_t seed; int result; } Game;

static Game *G_games; static int G_n; static int G_greedy=0;
static int G_next; static pthread_mutex_t G_mu=PTHREAD_MUTEX_INITIALIZER;

static void* worker(void* arg){
  long tid=(long)arg;
  for(;;){
    pthread_mutex_lock(&G_mu); int i=G_next++; pthread_mutex_unlock(&G_mu);
    if(i>=G_n) break;
    Game*g=&G_games[i]; State s=g->s0;
    if(G_greedy) g->result=play_game_greedy(&g->b,&s,g->seed);
    else g->result=play_game(&g->b,&s,g->seed, (uint64_t)0xABCDEF123ull*(i+1)+tid);
  }
  return NULL;
}

int main(int argc,char**argv){
  init_pcap(); init_ecap();
  int nthreads=8;
  for(int i=1;i<argc;i++){
    if(!strcmp(argv[i],"--greedy")) G_greedy=1;
    else if(!strcmp(argv[i],"--budget")) g_budget=atoi(argv[++i]);
    else if(!strcmp(argv[i],"--c")) g_c=atof(argv[++i]);
    else if(!strcmp(argv[i],"--threads")) nthreads=atoi(argv[++i]);
    else if(!strcmp(argv[i],"--floor")) RP_FLOOR=atof(argv[++i]);
    else if(!strcmp(argv[i],"--grow")) RP_GROW=atof(argv[++i]);
    else if(!strcmp(argv[i],"--pc")) RP_PC=atof(argv[++i]);
    else if(!strcmp(argv[i],"--lead")) RP_LEAD=atof(argv[++i]);
    else if(!strcmp(argv[i],"--maxatt")) g_maxAttacks=atoi(argv[++i]);
    else if(!strcmp(argv[i],"--margin")) g_stopMargin=atof(argv[++i]);
    else if(!strcmp(argv[i],"--tree")) g_use_tree=1;
    else if(!strcmp(argv[i],"--flat")) g_use_tree=0;
    else if(!strcmp(argv[i],"--tbudget")) g_tree_budget=atoi(argv[++i]);
    else if(!strcmp(argv[i],"--selmean")) g_selmean=1;
    else if(!strcmp(argv[i],"--minvis")) g_minVisits=atoi(argv[++i]);
    else if(!strcmp(argv[i],"--prior")) g_prior=1;
    else if(!strcmp(argv[i],"--cpuct")) g_cpuct=atof(argv[++i]);
    else if(!strcmp(argv[i],"--temp")) g_temp=atof(argv[++i]);
    else if(!strcmp(argv[i],"--fpu")) g_fpu=atof(argv[++i]);
    else if(!strcmp(argv[i],"--stoplogit")) g_stopLogit=atof(argv[++i]);
    else if(!strcmp(argv[i],"--srollout")) g_srollout=1;
    else if(!strcmp(argv[i],"--sprior")) g_strongprior=1;
    else if(!strcmp(argv[i],"--rollh")) g_rollhorizon=atoi(argv[++i]);
    else if(!strcmp(argv[i],"--leafeval")) g_leafeval=1;
    else if(!strcmp(argv[i],"--evref")) g_evRef=atof(argv[++i]);
    else if(!strcmp(argv[i],"--evscale")) g_evScale=atof(argv[++i]);
    else if(!strcmp(argv[i],"--vmix")) g_vmix=atof(argv[++i]);
    else if(!strcmp(argv[i],"--dumpfeat")){ g_dumpfeat=1; g_dumpf=fopen(argv[++i],"w"); }
    else if(!strcmp(argv[i],"--lprior")) load_lprior(argv[++i]);
    else if(!strcmp(argv[i],"--dumpval")){ g_dumpval=1; g_dumpvf=fopen(argv[++i],"w"); }
    else if(!strcmp(argv[i],"--dumpvf")){ g_dumpval=1; g_dumpvfmode=1; g_dumpvf=fopen(argv[++i],"w"); }
    else if(!strcmp(argv[i],"--vvalue")) load_vvalue(argv[++i]);
    else if(!strcmp(argv[i],"--lcb")) g_lcb=atof(argv[++i]);
    else if(!strcmp(argv[i],"--r2pen")) RP_2PEN=atof(argv[++i]);
  }
  // read boards: "B\n" then per board "seed N M\n" N×"owner str" M×"a b"
  int nb; if(scanf("%d",&nb)!=1){fprintf(stderr,"bad input\n");return 1;}
  G_games=calloc(nb,sizeof(Game)); G_n=nb;
  for(int i=0;i<nb;i++){
    Game*g=&G_games[i]; long long seed; int N,M;
    if(scanf("%lld %d %d",&seed,&N,&M)!=3){fprintf(stderr,"bad board %d\n",i);return 1;}
    g->seed=(uint64_t)seed; g->b.N=N;
    for(int j=0;j<N;j++){ g->b.deg[j]=0; int ow,st; scanf("%d %d",&ow,&st); g->s0.owner[j]=ow; g->s0.str[j]=st; }
    for(int j=0;j<M;j++){ int a,bb; scanf("%d %d",&a,&bb);
      g->b.adj[a][g->b.deg[a]++]=bb; g->b.adj[bb][g->b.deg[bb]++]=a; }
  }
  G_next=0;
  pthread_t th[64]; if(nthreads>64)nthreads=64;
  for(long t=0;t<nthreads;t++) pthread_create(&th[t],NULL,worker,(void*)t);
  for(int t=0;t<nthreads;t++) pthread_join(th[t],NULL);
  int wins=0; for(int i=0;i<nb;i++) if(G_games[i].result==0) wins++;
  printf("%d %d %.4f\n", wins, nb, (double)wins/nb);
  if(g_dec_count) fprintf(stderr,"  [timing] %ld decisions, %.2f ms/decision\n",
    g_dec_count, g_dec_ns/g_dec_count/1e6);
  return 0;
}
