F="--games 60 --seed-base 1"
run(){ printf "%-62s " "$*"; .venv/bin/python mcts.py $@ 2>&1 | grep -oE "winrate     : [0-9.]+%  \([0-9]+/[0-9]+\)" ; }
echo "== value-net baselines (seeds 1..60) =="
run "sl_cnn.pt $F --sims 120"
run "az2.pt $F --sims 120"
echo "== pure UCT (NO net at all): uniform priors + bot rollout =="
run "sl_cnn.pt $F --sims 100 --leaf rollout --priors uniform"
run "sl_cnn.pt $F --sims 400 --leaf rollout --priors uniform"
run "sl_cnn.pt $F --sims 1000 --leaf rollout --priors uniform"
echo "== no VALUE net: policy-net priors + bot rollout =="
run "sl_cnn.pt $F --sims 100 --leaf rollout --priors net"
run "sl_cnn.pt $F --sims 400 --leaf rollout --priors net"
run "sl_cnn.pt $F --sims 1000 --leaf rollout --priors net"
echo "== DONE =="
